name: chipwit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: 6.0.5
  bloc: 8.1.1
  cupertino_icons: 1.0.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  injectable: 2.1.1
  logger: 1.3.0

dev_dependencies:
  auto_route_generator: 6.0.3
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  injectable_generator: 2.1.5
  very_good_analysis: 4.0.0+1

flutter:
  uses-material-design: true
